from bs4 import BeautifulSoup
import markdownify
import re

def extract_clean_text(html_content: str) -> str:
    """
    Strips noise (navbars, footers, scripts, styles) from HTML content
    and returns a clean, structured Markdown representation of the Job Description.
    """
    if not html_content:
        return ""

    soup = BeautifulSoup(html_content, 'html.parser')

    # Remove all standard noise tags
    noise_tags = [
        'script', 'style', 'nav', 'footer', 'header', 'aside', 
        'noscript', 'iframe', 'svg', 'canvas', 'form'
    ]
    for tag in soup.find_all(noise_tags):
        tag.decompose()

    # Remove elements based on common noise-related class or id names
    noise_classes_ids = [
        'cookie', 'banner', 'sidebar', 'advertisement', 'promo', 
        'popup', 'modal', 'menu', 'social', 'newsletter', 'cta'
    ]
    
    # We use a compiled regex to match partial class/id names efficiently
    noise_pattern = re.compile('|'.join(noise_classes_ids), re.IGNORECASE)
    
    for element in soup.find_all(attrs={"class": noise_pattern}):
        element.decompose()
        
    for element in soup.find_all(attrs={"id": noise_pattern}):
        element.decompose()

    # Convert the cleaned HTML to Markdown
    # Use ATX headings (### instead of underlining) and strip excess whitespace
    markdown_text = markdownify.markdownify(str(soup), heading_style="ATX", strip=['img', 'a'])

    # Clean up excessive blank lines generated by removed elements
    # Replace 3 or more consecutive newlines with exactly 2 newlines
    clean_markdown = re.sub(r'\n{3,}', '\n\n', markdown_text)
    
    return clean_markdown.strip()
